"""
This type stub file was generated by pyright.
"""

import sys
import numpy as np
import cv2 as cv

__all__ = []
class Mat(np.ndarray):
    '''
    cv.Mat wrapper for numpy array.

    Stores extra metadata information how to interpret and process of numpy array for underlying C++ code.
    '''
    def __new__(cls, arr, **kwargs):
        ...
    
    def __init__(self, arr, **kwargs) -> None:
        ...
    
    def __array_finalize__(self, obj): # -> None:
        ...
    


