"""
This type stub file was generated by pyright.
"""

import cv2
from collections import namedtuple

NativeMethodPatchedResult = ...
def testOverwriteNativeMethod(arg): # -> Self@NativeMethodPatchedResult:
    ...

