"""
This type stub file was generated by pyright.
"""

import sys
import cv2 as cv

__all__ = ['op', 'kernel']
def register(mname): # -> (func: Unknown) -> Unknown:
    ...

@register('cv2.gapi')
def networks(*args):
    ...

@register('cv2.gapi')
def compile_args(*args): # -> list[Unknown]:
    ...

@register('cv2')
def GIn(*args): # -> list[Unknown]:
    ...

@register('cv2')
def GOut(*args): # -> list[Unknown]:
    ...

@register('cv2')
def gin(*args): # -> list[Unknown]:
    ...

@register('cv2.gapi')
def descr_of(*args): # -> list[Unknown]:
    ...

@register('cv2')
class GOpaque:
    def __new__(cls, argtype):
        ...
    
    class Bool:
        def __new__(self):
            ...
        
    
    
    class Int:
        def __new__(self):
            ...
        
    
    
    class Double:
        def __new__(self):
            ...
        
    
    
    class Float:
        def __new__(self):
            ...
        
    
    
    class String:
        def __new__(self):
            ...
        
    
    
    class Point:
        def __new__(self):
            ...
        
    
    
    class Point2f:
        def __new__(self):
            ...
        
    
    
    class Size:
        def __new__(self):
            ...
        
    
    
    class Rect:
        def __new__(self):
            ...
        
    
    
    class Prim:
        def __new__(self):
            ...
        
    
    
    class Any:
        def __new__(self):
            ...
        
    
    


@register('cv2')
class GArray:
    def __new__(cls, argtype):
        ...
    
    class Bool:
        def __new__(self):
            ...
        
    
    
    class Int:
        def __new__(self):
            ...
        
    
    
    class Double:
        def __new__(self):
            ...
        
    
    
    class Float:
        def __new__(self):
            ...
        
    
    
    class String:
        def __new__(self):
            ...
        
    
    
    class Point:
        def __new__(self):
            ...
        
    
    
    class Point2f:
        def __new__(self):
            ...
        
    
    
    class Size:
        def __new__(self):
            ...
        
    
    
    class Rect:
        def __new__(self):
            ...
        
    
    
    class Scalar:
        def __new__(self):
            ...
        
    
    
    class Mat:
        def __new__(self):
            ...
        
    
    
    class GMat:
        def __new__(self):
            ...
        
    
    
    class Prim:
        def __new__(self):
            ...
        
    
    
    class Any:
        def __new__(self):
            ...
        
    
    


def op(op_id, in_types, out_types): # -> (cls: Unknown) -> Unknown:
    ...

def kernel(op_cls): # -> (cls: Unknown) -> Unknown:
    ...

