"""
This type stub file was generated by pyright.
"""

import os
import importlib
import sys
from .cv2 import *
from .cv2 import _registerMatType
from . import data, gapi, mat_wrapper, misc, utils, version

'''
OpenCV Python binary extension loader
'''
__all__ = []
def bootstrap(): # -> None:
    ...

